name: z_permission_handler
description: 一个用于轻松管理和请求应用权限的 Flutter 插件（纯 Dart 实现）。
version: 0.0.12
homepage: https://github.com/Jazzzy126/z_permission_handler

environment:
  sdk: ^3.9.2
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: